# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.hl7v2.fr.trans-cda-mss
canonical: https://interop.esante.gouv.fr/ig/hl7v2/ans.hl7v2.fr.trans-cda-mss # the last part of canonical and id must be the same
name: HL7v2_trans_CDA_MSS # Should be an acronym
title: Volet Transmission au LPS de documents CDA provenant d'un courriel MSSanté
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 1.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: "Accueil"
    cas-usage.md:
        title: "Cas d'usage"
    contexte-metier.md:
        title: "Organisation métier"
    acteurs-transactions.md:
        title: "Acteurs et transactions"
    def-proc-collab.md:
        title: "Définition des processus collaboratifs"
    identification-flux.md:
        title: "identification des flux"
    volume2.md:
    perimetre-transaction.md:
        title: "Périmètre de la transaction"
    role.md:
        title: "Rôle des acteurs pour cette transaction"
    standards.md:
        title: "Choix des standards"
    evenements-declenchants.md:
        title: "Evènements déclenchants"
    interactions-acteurs.md:
        title: "Interactions entre les Acteurs"
    profils-messages.md:
        title: "Profils de messages"
    lien-entete-cda-meta-xds.md:
        title: "Lien entre l'en-tête CDA et les métadonnées XDS"
    testplan.md:
        title: "Test Plan"
    issues.md:
        title: "Issues"
    meta-dmp-mss.md:
        title: "Table MetaDMP/MSS"
    error-codes.md:
        title: "Codes erreurs de traitement du message HL7 MDM"    
    exemples.md:
        title: "Exemples de messages"
    struct-msg-mdn.md:
        title: "Structure du message MDN (MSSanté)"
    change-log.md:
        title: "Historique des versions"
    glossaire.md:
        title: "Glossaire"
    download.md:
        title: "Téléchargements"
        generation: markdown

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: 
        "Cas d'usage": cas-usage.html
        "Organisation métier": contexte-metier.html
        "Acteurs et transactions": acteurs-transactions.html
        "Définition des processus collaboratifs": def-proc-collab.html
        "identification des flux": identification-flux.html
    Volume 2 – Détail des Transactions: 
        "Volume 2 : Introduction": volume2.html
        "Périmètre de la transaction": perimetre-transaction.html
        "Rôle des acteurs pour cette transaction": role.html
        "Choix des standards": standards.html
        "Evènements déclenchants": evenements-declenchants.html
        "Interactions entre les Acteurs": interactions-acteurs.html
        "Profils de messages": profils-messages.html
        "Lien entre l'en-tête CDA et les métadonnées XDS": lien-entete-cda-meta-xds.html
    Volume 3:
        "Table MetaDMP/MSS": meta-dmp-mss.html
        "Codes erreurs de traitement du message HL7 MDM": error-codes.html
        "Exemples de messages": exemples.html
        "Structure du message MDN (MSS)": struct-msg-mdn.html
        "Glossaire": glossaire.html
    Test Plan: testplan.html
    Historique des versions: change-log.html
    Téléchargements: download.html
 #   Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/